#!/bin/bash
# Zeno Labs: Automated VDP Report Generator

if [ "$#" -ne 2 ]; then
    echo "Usage: ./zeno_audit.sh <VULNERABLE_DOMAIN> <DANGLING_CNAME>"
    exit 1
fi

DOMAIN=$1
CNAME=$2
DATE=$(date +"%B %d, %Y")
OUTPUT_FILE="usss_audit_$(date +"%Y%m%d").md"

echo "Generating Vulnerability Disclosure Report for $DOMAIN..."

cat << REPORT > "$OUTPUT_FILE"
# Vulnerability Disclosure Report: Subdomain Takeover

**Date:** $DATE
**Author:** Zacheriah Alan Potter (Zeno Labs)
**Target Domain:** \`$DOMAIN\`
**Vulnerability Type:** Subdomain Takeover via Dangling CNAME (CWE-400)
**Severity:** High

---

## 1. Description
During routine passive DNS reconnaissance, a dangling CNAME record was identified on the target domain. The domain \`$DOMAIN\` currently points to \`$CNAME\`.

However, the Azure resource at \`$CNAME\` appears to be de-provisioned or deleted. This leaves the domain vulnerable to a Subdomain Takeover. A malicious actor could register the exact resource name within their own Azure tenant and effectively seize control of the content hosted at \`$DOMAIN\`.

## 2. Steps to Reproduce
This finding was discovered passively. No active exploitation or resource claiming was performed, in strict adherence to safe harbor guidelines.
1. Perform a DNS query for the target domain:
   \`dig $DOMAIN CNAME +short\`
2. Observe the output pointing to the vulnerable cloud provider:
   \`$CNAME\`
3. Verify via HTTP/HTTPS that the endpoint returns a standard "Resource Not Found" error indicative of a dangling cloud route.

## 3. Security Impact
If exploited, an attacker gains complete control over the subdomain. Because the domain carries the high-trust \`.gov\` top-level domain, the attacker could use this for:
* Launching highly credible spear-phishing campaigns.
* Bypassing Same-Origin Policy (SOP) to steal cookies or session tokens.
* Distributing malware masked as legitimate government software.

## 4. Remediation Recommendation
To resolve this vulnerability, please remove the dangling CNAME record (\`$CNAME\`) from the DNS zone file for \`$DOMAIN\` immediately.

---
*Report auto-generated by Zeno Labs Telemetry.*
REPORT

echo "Report successfully generated: $OUTPUT_FILE"
